import { StyleSheet } from 'react-native';
import { Palette as color } from '@/constants';
import Tokens, { Spacing, Radius, FontSize, Elevation, Shadow, Button } from '@/constants/designTokens';


const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: color.background,
    },
    card: {
        padding: Tokens.Spacing.xxl,
        borderRadius: Radius.lg,
        alignItems: 'center',
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: Elevation.card,
        backgroundColor: color.card,
        shadowColor: Shadow.light,
    },
    icon: {
        fontSize: 48,
        marginBottom: Spacing.md,
    },
    title: {
        fontSize: FontSize.h1,
        fontWeight: 'bold',
        marginBottom: 6,
        color: color.text,
    },
    subtitle: {
        fontSize: FontSize.body,
        marginBottom: Spacing.xl,
        textAlign: 'center',
        color: color.mutedText,
    },
    overlay: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: color.overlayDark,
    },
    button: {
        backgroundColor: color.background,
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.md,
        borderRadius: Button.radius,
        alignItems: 'center',
    },
    buttonText: {
        color: color.text,
        textAlign: 'center',
        fontSize: FontSize.body,
        fontWeight: '600',
    },
    keyboardAvoidingView: {
        flex: 1,
        justifyContent: 'center',
        padding: 20,
    },
    logoContainer: {
        alignItems: 'center',
        marginBottom: Spacing.xxl,
    },
    logoPlaceholder: {
        width: 80,
        height: 80,
        borderRadius: Spacing.xl,
        backgroundColor: color.card,
        justifyContent: 'center',
        alignItems: 'center',
    },
    logoText: {
        color: color.lightText,
        fontWeight: 'bold',
    },
    formContainer: {
        backgroundColor: color.lightGray,
        borderRadius: Radius.md,
        padding: Spacing.lg,
        shadowColor: Shadow.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: Elevation.card,
    },
    inputContainer: {
        flexDirection: 'row',
        borderWidth: 1,
        borderColor: color.borderColor,
        borderRadius: Radius.md,
        marginBottom: Spacing.lg,
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.md,
        alignItems: 'center',
        backgroundColor: color.lightGray,
    },
    inputIcon: {
        marginRight: Spacing.sm,
    },
    input: {
        flex: 1,
        fontSize: FontSize.body,
        color: color.text,
    },
    eyeIcon: {
        padding: Spacing.xs,
    },
    errorContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 10,
        borderRadius: Radius.sm,
        marginBottom: Spacing.lg,
    },
    error: {
        color: color.error,
        marginLeft: Spacing.sm,
        fontSize: FontSize.small,
    },
    loginButton: {
        backgroundColor: color.card,
        borderRadius: Radius.md,
        paddingVertical: Button.paddingVertical,
        alignItems: 'center',
        marginBottom: Spacing.xl,
    },
});

export const HomePagestyles = StyleSheet.create({
    container: {
        ...styles.container,
        paddingTop: 0,
    },
    contentContainer: {
        flex: 1,
        alignItems: 'center',
    },
    loadingContainer: {
        ...styles.container,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        marginTop: Spacing.md,
        fontSize: FontSize.body,
        color: color.loadingText,
    },
    headerSection: {
        width: '100%',
        alignItems: 'center',
        paddingTop: Spacing.xxl,
        paddingBottom: Spacing.xl,
        paddingHorizontal: Spacing.xl,
        borderBottomLeftRadius: Radius.lg,
        borderBottomRightRadius: Radius.lg,
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
        marginBottom: Spacing.xl,
    },
    heroGradient: {
        width: '100%',
        paddingTop: Spacing.xxl + 20,
        paddingBottom: Spacing.xl,
        paddingHorizontal: Spacing.xl,
        alignItems: 'center',
        borderBottomLeftRadius: Radius.lg,
        borderBottomRightRadius: Radius.lg,
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 8 },
        shadowOpacity: 0.25,
        shadowRadius: 15,
        elevation: 10,
        marginBottom: Spacing.xl,
    },
    mainContent: {
        flex: 1,
        width: '100%',
        paddingHorizontal: Spacing.xl,
    },
    userCard: {
        width: '100%',
        backgroundColor: color.lightBackground,
        borderRadius: Radius.lg,
        padding: Spacing.lg,
        marginBottom: Spacing.lg,
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
        borderLeftWidth: 4,
        borderLeftColor: color.primary,
    },
    userInfoContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    userAvatar: {
        width: 56,
        height: 56,
        borderRadius: 28,
        marginRight: Spacing.md,
        overflow: 'hidden',
        backgroundColor: color.lightGray,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 3,
        borderColor: color.primary,
    },
    userInfo: {
        flex: 1,
    },
    userName: {
        fontSize: FontSize.h3,
        fontWeight: '700',
        color: color.title,
        marginBottom: 2,
    },
    userEmail: {
        fontSize: FontSize.small,
        color: color.mutedText,
        marginBottom: 4,
    },
    userRole: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
    },
    roleText: {
        fontSize: FontSize.small,
        color: color.mutedText,
        marginRight: Spacing.sm,
    },
    vipBadge: {
        backgroundColor: color.primary,
        paddingHorizontal: Spacing.sm,
        paddingVertical: 2,
        borderRadius: Radius.sm,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
        elevation: 2,
    },
    vipText: {
        fontSize: 10,
        color: color.lightText,
        fontWeight: '700',
        marginLeft: 2,
    },
    buttonsSection: {
        width: '100%',
        marginBottom: Spacing.xl,
    },
    actionsCard: {
        width: '100%',
        backgroundColor: color.lightBackground,
        borderRadius: Radius.lg,
        padding: Spacing.lg,
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
    },
    footerSection: {
        width: '100%',
        alignItems: 'center',
        paddingVertical: Spacing.lg,
        backgroundColor: color.lightGray,
    },
    icon: {
        marginBottom: Spacing.md,
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        padding: Spacing.md,
        borderRadius: Radius.round,
    },
    title: {
        fontSize: FontSize.h1,
        fontWeight: '800',
        color: color.lightText,
        marginBottom: Spacing.xs,
        textAlign: 'center',
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    subtitle: {
        fontSize: FontSize.body,
        color: 'rgba(255, 255, 255, 0.9)',
        textAlign: 'center',
        fontWeight: '500',
    },
    startGameButton: {
        backgroundColor: color.success,
        borderRadius: Radius.md,
        shadowColor: color.shadowDark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
        marginBottom: Spacing.md,
    },
    buttonGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginTop: Spacing.sm,
    },
    gridButton: {
        width: '48%',
        marginBottom: Spacing.sm,
        borderColor: color.info,
        backgroundColor: 'transparent',
    },
    logoutButton: {
        width: '100%',
        marginTop: Spacing.md,
        borderColor: color.error,
        backgroundColor: 'transparent',
    },

    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        padding: Spacing.xl,
    },
    footerText: {
        fontSize: FontSize.small,
        color: color.mutedText,
        textAlign: 'center',
    },
});

export const GamePlayerRankstyles = StyleSheet.create({
    container: {
        ...styles.container,
    },
    header: {
        backgroundColor: color.lightBackground,
        padding: Spacing.lg,
        paddingBottom: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: color.borderColor,
    },
    title: {
        fontSize: FontSize.h2,
        fontWeight: 'bold',
        color: color.valueText,
        marginBottom: Spacing.md,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: color.lightGray,
        borderRadius: Radius.md,
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.sm,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        marginLeft: Spacing.sm,
        color: color.valueText,
    },
    sortContainer: {
        backgroundColor: color.background,
        padding: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: color.borderColor,
    },
    sortLabel: {
        fontSize: 14,
        color: color.valueLabel,
        marginBottom: Spacing.sm,
    },
    sortButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    sortButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: color.lightGray,
        borderRadius: Radius.sm,
        paddingVertical: 8,
        paddingHorizontal: Spacing.md,
        flex: 1,
        marginHorizontal: 4,
        justifyContent: 'center',
    },
    sortButtonActive: {
        backgroundColor: color.primary,
    },
    sortButtonText: {
        fontSize: FontSize.small,
        color: color.text,
        marginLeft: 4,
    },
    sortButtonTextActive: {
        color: color.lightText,
        fontWeight: '600',
    },
    list: {
        padding: Spacing.md,
        paddingBottom: Spacing.xl,
    },
    playerCard: {
        backgroundColor: color.lightBackground,
        borderRadius: Radius.md,
        marginBottom: Spacing.md,
        overflow: 'hidden',
        elevation: 2,
        shadowColor: color.shadowDark,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    topPlayerCard: {
        borderLeftWidth: 3,
        borderLeftColor: color.card,
    },
    playerHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: color.lightGray,
    },
    rankBadge: {
        width: 24,
        height: 24,
        borderRadius: Radius.md,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: Spacing.sm,
    },
    rankBadgeText: {
        fontSize: FontSize.small,
        fontWeight: 'bold',
        color: color.lightText,
    },
    avatar: {
        width: 36,
        height: 36,
        borderRadius: Radius.md,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: Spacing.sm,
        overflow: 'hidden',
    },
    avatarImage: {
        width: '100%',
        height: '100%',
        borderRadius: Radius.lg,
    },
    avatarFallback: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: Radius.lg,
    },
    avatarText: {
        fontSize: FontSize.h3,
        fontWeight: 'bold',
        color: color.lightText,
    },
    nameContainer: {
        flex: 1,
    },
    playerName: {
        fontSize: FontSize.body,
        fontWeight: '600',
        color: color.valueText,
    },
    gamesContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: Spacing.xs,
    },
    gamesText: {
        fontSize: FontSize.small,
        color: color.valueLabel,
        marginLeft: Spacing.xs,
    },
    profitBadge: {
        paddingHorizontal: Spacing.md,
        paddingVertical: Spacing.xs,
        borderRadius: Radius.sm,
    },
    profitText: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
    },
    statItem: {
        flex: 1,
        flexDirection: 'row',
    },
    statsContainer: {
        flexDirection: 'row',
        padding: Spacing.md,
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: 8,
        backgroundColor: color.lightBackground,
    },
    statTexts: {
        marginLeft: Spacing.sm,
        justifyContent: 'center',
    },
    // searchInput defined earlier for GamePlayerRankstyles
    statValue: {
        fontSize: FontSize.small,
        fontWeight: '600',
        color: color.valueText,
    },
    statLabel: {
        fontSize: FontSize.small,
        color: color.valueLabel,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: Spacing.xl,
    },
    loadingText: {
        marginTop: Spacing.md,
        fontSize: FontSize.small,
        color: color.valueLabel,
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: Spacing.xxl,
        marginTop: Spacing.xxl,
    },
    emptyTitle: {
        fontSize: FontSize.h3,
        fontWeight: '600',
        color: color.valueLabel,
        marginTop: Spacing.lg,
    },
    emptyText: {
        fontSize: FontSize.body,
        color: color.weakGray,
        marginTop: Spacing.sm,
        textAlign: 'center',
    },

});

export const GamePlaystyles = StyleSheet.create({
    container: {
        flex: 1,

    },
    toolsSection: {
        backgroundColor: 'transparent',
        marginBottom: Spacing.lg,
        paddingHorizontal: Spacing.lg,
        paddingVertical: Spacing.md,
        borderBottomWidth: 1,
        borderBottomColor: color.borderColor,
    },
    toolsHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: Spacing.sm,
    },
    toolsTitle: {
        fontSize: FontSize.small,
        fontWeight: '600',
        color: color.title,
        marginLeft: Spacing.xs,
        letterSpacing: 0.5,
    },
    buttonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        gap: Spacing.sm,
        width: '100%',
    },
    toolButton: {
        flex: 1,
        borderRadius: Radius.md,
        overflow: 'hidden',
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.15,
        shadowRadius: 8,
        elevation: 5,
    },
    toolButtonGradient: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.sm,
    },
    toolButtonText: {
        color: color.lightText,
        fontWeight: '700',
        fontSize: FontSize.small,
        marginLeft: Spacing.xs,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 2,
    },
    timerButton: {},
    calculatorButton: {},
    wheelButton: {},
    statusHeader: {
        flexDirection: 'row',
        marginBottom: Spacing.md,
        alignItems: 'center',
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: color.lightGray,
        paddingVertical: Spacing.xs,
        paddingHorizontal: Spacing.md,
        borderRadius: Radius.lg,
        borderWidth: 1,
        borderColor: color.borderColor,
    },
    statusText: {
        fontSize: FontSize.small,
        color: color.primary,
        fontWeight: '500',
        marginLeft: Spacing.sm,
    },
    list: {
        paddingHorizontal: Spacing.lg,
        paddingBottom: Spacing.xl,
    },
    overlay: {
        flex: 1,
        justifyContent: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        padding: Spacing.xl,
    },
    analysisCard: {
        borderRadius: Radius.lg,
        backgroundColor: color.lightBackground,
        marginVertical: Spacing.lg,
        overflow: 'hidden',
        shadowColor: color.shadowLight,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        elevation: 6,
        borderWidth: 1,
        borderColor: 'rgba(0, 0, 0, 0.06)',
    },
    analysisHeader: {
        paddingVertical: Spacing.lg,
        paddingHorizontal: Spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(0, 0, 0, 0.08)',
    },
    analysisTitle: {
        fontSize: FontSize.h2,
        fontWeight: '800',
        marginLeft: Spacing.sm,
        color: color.title,
    },
    analysisCardContainer: {
        padding: Spacing.lg,
        backgroundColor: '#FEFEFE',
    },
    analysisSectionContainer: {
        gap: Spacing.md,
    },
    endGameButton: {
        backgroundColor: color.error,
        borderRadius: Radius.md,
        height: 56,
        shadowColor: color.shadowDark,
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.3,
        shadowRadius: 12,
        elevation: 8,
    },
    endGameButtonText: {
        fontSize: FontSize.h3,
        fontWeight: '800',
        color: color.lightText,
        letterSpacing: 1,
        textShadowColor: 'rgba(0, 0, 0, 0.3)',
        textShadowOffset: { width: 0, height: 2 },
        textShadowRadius: 4,
    },
    headerButton: {
        padding: Spacing.sm,
        borderRadius: Radius.sm,
    },
    summaryModal: {
        backgroundColor: color.lightBackground,
        marginHorizontal: Spacing.lg,
        borderRadius: Radius.lg,
        padding: Spacing.lg,
        elevation: Elevation.overlay,
    },
    summaryTitle: {
        fontSize: FontSize.h2,
        fontWeight: 'bold',
        textAlign: 'center',
        marginBottom: Spacing.md,
    },
    summaryRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingVertical: Spacing.sm,
        borderBottomWidth: 0.5,
        borderColor: color.weakGray,
    },
    summaryName: {
        flex: 1,
        fontWeight: '500',
    },
    summaryValue: {
        width: 80,
        textAlign: 'right',
    },
    summaryButtonRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: Spacing.lg,
    },
    summaryCancelButton: {
        flex: 1,
        marginRight: Spacing.sm,
        backgroundColor: color.weakGray,
    },
    summaryConfirmButton: {
        flex: 1,
        marginLeft: Spacing.sm,
    },

});

export const GameHistorystyles = StyleSheet.create({
    container: {
        ...styles.container,
    },
    list: {
        padding: Spacing.lg,
        paddingBottom: Spacing.xl,
    },
    loadingContainer: {
        ...HomePagestyles.loadingContainer,
    },
    loadingText: {
        ...HomePagestyles.loadingText
    },
    card: {
        backgroundColor: color.mediumGray,
        borderRadius: Radius.md,
        marginBottom: Spacing.md,
        overflow: 'hidden',
        elevation: 3,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        flexDirection: 'row',
    },
    dateContainer: {
        width: 70,
        backgroundColor: color.weakGray,
        padding: Spacing.md,
        alignItems: 'center',
        justifyContent: 'center',
        borderRightWidth: 1,
        borderRightColor: color.borderColor,
    },
    dateBox: {
        alignItems: 'center',
    },
    dateText: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: color.strongGray,
    },
    monthText: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: color.strongGray,
    },
    yearText: {
        fontSize: FontSize.small,
        color: color.strongGray,
        marginTop: 2,
    },
    timeText: {
        fontSize: FontSize.small,
        color: color.strongGray,
        marginTop: 8,
    },
    cardContent: {
        flex: 1,
        padding: Spacing.md,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Spacing.md,
    },
    blindsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: color.lightGray,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: Spacing.md,
    },
    blindsText: {
        fontSize: 14,
        fontWeight: '600',
        color: color.valueText,
        marginLeft: 4,
    },
    playerCountContainer: {
        backgroundColor: color.lightBackground,
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: Spacing.md,
    },
    playerCountText: {
        fontSize: 13,
        color: color.success,
        fontWeight: '500',
    },
    statsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: color.lightGray,
        borderRadius: Spacing.md,
        padding: 8,
        marginBottom: Spacing.md,
    },
    statItem: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 4,
    },
    statTexts: {
        marginLeft: Spacing.sm,
    },
    statValue: {
        fontSize: 14,
        fontWeight: '600',
        color: color.valueText,
    },
    statLabel: {
        fontSize: 11,
        color: color.valueLabel,
    },
    playersContainer: {
        backgroundColor: color.lightGray,
        borderRadius: Spacing.md,
        padding: 10,
        marginBottom: Spacing.sm,
    },
    playerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    playerInfo: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    playerName: {
        fontSize: 13,
        color: color.valueText,
        marginLeft: Spacing.sm,
    },
    playerProfit: {
        fontSize: 13,
        fontWeight: '600',
    },
    cardFooter: {
        alignItems: 'flex-end',
    },
    emptyContainer: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 40,
    },
    emptyText: {
        fontSize: 18,
        fontWeight: '600',
        color: '#757575',
        marginTop: 16,
    },
    emptySubText: {
        fontSize: 14,
        color: '#9E9E9E',
        marginTop: 8,
    },
});

export const GameDetailstyles = StyleSheet.create({
    container: {
        ...styles.container,
    },
    scrollContent: {
        padding: 0,
        paddingBottom: 24,
    },
    notFoundContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
        backgroundColor: color.background,
    },
    notFound: {
        fontSize: 18,
        color: color.text,
        textAlign: 'center',
        marginTop: Spacing.md,
        marginBottom: 24,
    },
    backButton: {
        backgroundColor: color.card,
        paddingHorizontal: 24,
    },
    backButtonText: {
        color: '#34495e',
    },
    header: {
        backgroundColor: color.primary,
        padding: 16,
        borderBottomLeftRadius: 20,
        borderBottomRightRadius: 20,
    },
    gameInfoHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    dateTimeContainer: {
        backgroundColor: 'rgba(255, 255, 255, 0.2)',
        paddingHorizontal: Spacing.md,
        paddingVertical: 6,
        borderRadius: Radius.sm,
    },
    dateText: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: color.lightText,
    },
    timeText: {
        fontSize: FontSize.small,
        color: color.lightText,
        opacity: 0.9,
    },
    blindContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(0, 0, 0, 0.2)',
        paddingHorizontal: Spacing.md,
        paddingVertical: 8,
        borderRadius: Radius.sm,
    },
    blindText: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: color.lightText,
        marginLeft: Spacing.sm,
    },
    gameIdText: {
        fontSize: FontSize.small,
        color: 'rgba(255, 255, 255, 0.7)',
        marginTop: Spacing.md,
    },
    summaryContainer: {
        margin: 16,
        backgroundColor: color.lightText,
        borderRadius: Spacing.md,
        padding: 16,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    summaryHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: Spacing.md,
    },
    summaryTitle: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: color.text,
        marginLeft: Spacing.sm,
    },
    statsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        marginBottom: Spacing.md,
    },
    statBox: {
        width: '48%',
        backgroundColor: '#f8f9fa',
        borderRadius: Radius.sm,
        padding: Spacing.md,
        marginBottom: Spacing.sm,
        alignItems: 'center',
    },
    statValue: {
        fontSize: 18,
        fontWeight: 'bold',
        color: color.valueText,
    },
    statLabel: {
        fontSize: FontSize.small,
        color: color.valueLabel,
        marginTop: 4,
    },
    exchangeRate: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#ecf0f1',
        padding: 8,
        borderRadius: Radius.sm,
        marginTop: 4,
    },
    exchangeText: {
        fontSize: FontSize.small,
        color: '#34495e',
        marginLeft: Spacing.sm,
    },
    highlightsContainer: {
        marginHorizontal: Spacing.lg,
        marginBottom: Spacing.lg,
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    highlightCard: {
        backgroundColor: color.lightText,
        borderRadius: Spacing.md,
        padding: Spacing.md,
        width: '48%',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    highlightHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: Spacing.sm,
    },
    highlightTitle: {
        fontSize: FontSize.small,
        fontWeight: '600',
        color: color.valueText,
        marginLeft: Spacing.xs,
    },
    highlightContent: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 36,
        height: 36,
        borderRadius: Radius.lg,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarText: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: 'white',
    },
    highlightInfo: {
        marginLeft: Spacing.sm,
        flex: 1,
    },
    highlightName: {
        fontSize: FontSize.small,
        fontWeight: '600',
        color: color.valueText,
    },
    highlightProfit: {
        fontSize: FontSize.small,
        fontWeight: 'bold',
        color: color.success,
    },
    highlightCash: {
        fontSize: FontSize.small,
        color: color.success,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: Spacing.lg,
        marginBottom: Spacing.sm,
    },
    sectionTitle: {
        fontSize: FontSize.body,
        fontWeight: 'bold',
        color: color.valueText,
        marginLeft: Spacing.sm,
    },
    playerListContainer: {
        paddingHorizontal: Spacing.lg,
    },
    playerCard: {
        backgroundColor: color.lightText,
        borderRadius: Spacing.md,
        padding: Spacing.md,
        marginBottom: Spacing.md,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    playerCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: Spacing.md,
    },
    playerIdentity: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    playerName: {
        marginLeft: Spacing.sm,
        fontSize: FontSize.body,
        fontWeight: '600',
        color: color.valueText,
    },

    playerStats: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: Spacing.sm,
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    playerStatItem: {
        width: '45%',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: Spacing.xs,
        backgroundColor: color.mediumGray,
        paddingHorizontal: Spacing.sm,
        gap: Spacing.sm,
        borderRadius: Radius.sm,
        marginBottom: Spacing.sm,
        marginRight: Spacing.sm,

    },
    playerStatTexts: {
        marginLeft: Spacing.sm,

    },
    playerStatValue: {
        fontSize: 14,
        fontWeight: '600',
        color: color.valueText,
    },
    playerStatLabel: {
        fontSize: 11,
        color: color.valueLabel,
    },
    playerCashResult: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'flex-end',
        backgroundColor: color.lightGray,
        paddingHorizontal: Spacing.md,
        paddingVertical: 6,
        borderRadius: Radius.sm,
        alignSelf: 'flex-end',
    },
    playerCashText: {
        fontSize: 14,
        fontWeight: 'bold',
        marginLeft: Spacing.sm,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginHorizontal: Spacing.lg,
        marginTop: 16,
    },
    copyButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: color.info,
        borderRadius: Radius.sm,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.lg,
        flex: 1,
        marginRight: Spacing.sm,
        elevation: 2,
        shadowColor: color.shadowDark,
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
    },
    emailButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: color.info,
        borderRadius: Radius.sm,
        paddingVertical: Spacing.md,
        paddingHorizontal: Spacing.lg,
        flex: 1,
        marginLeft: Spacing.sm,
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 1.5,
    },
    buttonDisabled: {
        backgroundColor: color.strongGray,
        elevation: 0,
        shadowOpacity: 0,
    },
    actionButtonText: {
        fontSize: FontSize.small,
        fontWeight: '600',
        color: color.lightText,
        marginLeft: Spacing.sm,
    },
    avatarImage: {
        width: '100%',
        height: '100%',
        borderRadius: Spacing.xl
    },
    avatarFallback: {
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: Spacing.xl
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: color.overlayDark,
        justifyContent: 'center',
        padding: Spacing.lg
    },
});
export default styles;